name: mt_app
description: MT simple test app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #Text animations
  animated_text_kit: ^4.2.2

  #For icons
  font_awesome_flutter: ^10.2.1

  #To get pick image
  image_picker: ^0.8.6

  #To get document storage path
  path_provider: ^2.0.11

  #Date formatting
  intl: ^0.17.0

  #Device info
  device_information: ^0.0.4

  #To handle permissions
  permission_handler: ^10.1.0

  #To get location
  geolocator: ^9.0.2

  #For SQL db
  sqflite: ^2.1.0+1

  get_it: ^7.2.0

  flutter_bloc: ^8.1.1

  equatable: ^2.0.5

  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
